services:
  - type: web
    name: veritas-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: JWT_SECRET
        generateValue: true
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1